### ISSUE TITLE
Scientific Recommendation Testing

### ISSUE THREAD

**Issue by jaswellnitz** [jaswellnitz/tourist-chatbot#51]
Test recommendation mechanism for statistical significance.

**Comment by bbaruque** [comment]
Some ideas:

https://buildingrecommenders.wordpress.com/2016/02/04/testing-recommenders/
https://www.r-bloggers.com/testing-recommender-systems-in-r/
http://ir.ii.uam.es/~alejandro/2011/recsys-poster.pdf 

The last one is especially interesting

**Comment by bbaruque** [comment]
In this Tutorial: https://de.slideshare.net/Cataldo/tutoria-mahout-recommendation  
You can find a pre-defined way of doing the more common tests (from slide 48 onwards)
